y = Msgbox("Your pc has been hacked",48, "WARNING!!!")
x = Msgbox("Your computer has been infected by a virus",48,"WARNING!!!")
y = Msgbox("Virus has infected the hard drive (C:). Deletion of the virus will require complete formatting of the hard drive (C:). Would you like to format hard drive? (C:)",48+4, "WARNING!!!")
z = Msgbox("To avoid deletion of files, kindly answer these questions")
h = Msgbox("will...",32,"<3")
a = Msgbox("you be...",32,"<3")
b = Msgbox("my valentine ? ^-^",4+16,"<3")
b = Msgbox("Thank youuu, I love youuu <3")
